export const PERMISSIONS = [
  "profile.read_own",
  "courses.read_own",
  "assessments.read_own",
  "results.read_published_own",
  "notices.read",
  "password.change_own",
  "courses.read_assigned",
  "enrolments.read_assigned",
  "assessments.create_assigned",
  "assessments.update_assigned",
  "grades.create_assigned",
  "grades.update_draft_assigned",
  "grades.submit_assigned",
  "courses.read_department",
  "grades.read_department",
  "grades.approve_department",
  "grades.reject_department",
  "students.manage",
  "programmes.manage",
  "courses.manage",
  "enrolments.manage",
  "results.review",
  "results.publish",
  "grade_changes.approve",
  "academic_periods.manage",
  "users.create",
  "users.disable",
  "roles.assign",
  "permissions.manage",
  "system.configure",
  "audit_logs.read",
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];
