"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import type { AdminAssignmentView, AdminOfferingView, AdminStaffView } from "@/features/admin/admin-data";

export function LecturerAssignmentControls({ staff, offerings, assignments }: { staff: AdminStaffView[]; offerings: AdminOfferingView[]; assignments: AdminAssignmentView[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  function send(payload: Record<string, string>) { setMessage(null); startTransition(async () => { const response = await fetch("/api/admin/assignments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { error?: string; message?: string }; setMessage(result.error ?? result.message ?? null); if (response.ok) router.refresh(); }); }
  return <div className="space-y-5">{message ? <p className="rounded-xl bg-muted px-4 py-3 text-sm font-bold text-navy">{message}</p> : null}<form className="rounded-2xl border border-border bg-white p-6 shadow-sm" onSubmit={(event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); send({ action: "assign", courseOfferingId: String(values.courseOfferingId), staffMemberId: String(values.staffMemberId) }); }}><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-navy">Course offering<select name="courseOfferingId" required className="h-11 rounded-xl border border-border bg-white px-3"><option value="">Select offering</option>{offerings.map((offering) => <option key={offering.id} value={offering.id}>{offering.courseLabel} · {offering.periodLabel}</option>)}</select></label><label className="grid gap-2 text-sm font-bold text-navy">Lecturer / staff member<select name="staffMemberId" required className="h-11 rounded-xl border border-border bg-white px-3"><option value="">Select lecturer</option>{staff.map((member) => <option key={member.id} value={member.id}>{member.staff_number} — {member.name}</option>)}</select></label></div><Button className="mt-5" type="submit" disabled={pending}>Assign lecturer</Button></form><section className="overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div className="border-b border-border px-6 py-4"><h2 className="font-extrabold text-navy">Current assignments</h2></div><div className="divide-y divide-border">{assignments.map((assignment) => <div key={assignment.id} className="flex flex-col justify-between gap-3 px-6 py-4 sm:flex-row sm:items-center"><div><p className="font-extrabold text-navy">{assignment.offeringLabel}</p><p className="text-sm text-muted-foreground">{assignment.staffNumber} — {assignment.lecturerName}</p></div><Button variant="danger" disabled={pending} onClick={() => send({ action: "remove", assignmentId: assignment.id })}>Remove assignment</Button></div>)}</div></section></div>;
}
