"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import type { AdminStudentView } from "@/features/admin/admin-data";
import type { ProgrammeRow } from "@/types/database";

export function StudentSetupControls({ students, programmes }: { students: AdminStudentView[]; programmes: ProgrammeRow[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  function submit(form: HTMLFormElement) { const payload = Object.fromEntries(new FormData(form)); setMessage(null); startTransition(async () => { const response = await fetch("/api/admin/students", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { error?: string; message?: string }; setMessage(result.error ?? result.message ?? null); if (response.ok) router.refresh(); }); }
  return <div className="space-y-4">{message ? <p className="rounded-xl bg-muted px-4 py-3 text-sm font-bold text-navy">{message}</p> : null}{students.map((student) => <form key={student.id} className="rounded-2xl border border-border bg-white p-5 shadow-sm" onSubmit={(event) => { event.preventDefault(); submit(event.currentTarget); }}><input type="hidden" name="studentId" value={student.id} /><div className="grid gap-4 xl:grid-cols-[1.3fr_1.2fr_120px_170px_auto] xl:items-end"><div><p className="font-mono text-xs font-extrabold text-primary">{student.registration_number}</p><p className="mt-1 font-extrabold text-navy">{student.name}</p><p className="text-sm text-muted-foreground">{student.email}</p></div><label className="grid gap-1.5 text-sm font-bold text-navy">Programme<select name="programmeId" defaultValue={student.programme_id} className="h-11 rounded-xl border border-border bg-white px-3">{programmes.map((programme) => <option key={programme.id} value={programme.id}>{programme.code} — {programme.name}</option>)}</select></label><label className="grid gap-1.5 text-sm font-bold text-navy">Year<input name="yearOfStudy" type="number" min={1} defaultValue={student.year_of_study} className="h-11 rounded-xl border border-border px-3" /></label><label className="grid gap-1.5 text-sm font-bold text-navy">Academic status<select name="status" defaultValue={student.student_status} className="h-11 rounded-xl border border-border bg-white px-3"><option value="active">Active</option><option value="suspended">Suspended</option><option value="withdrawn">Withdrawn</option><option value="completed">Completed</option><option value="graduated">Graduated</option></select></label><Button type="submit" disabled={pending}>Save setup</Button></div></form>)}</div>;
}
